exception: call free_heap_page() in handle_kdb_enter()
The affected code isn't being tested automagically because the function would
be interactive, and in the absence of a Pistachio-style in-kernel debugger
there's no use for it anyway. So this changeset doesn't necessarily do
anything useful.