exception: always require @utcb != NULL in set_pf_msg()
As per its actual use (, duh).

Also, removed some #if 0'd segments from the I/O fault handler.