exception: enable/disable trace prints w/ special KDB_PrintString()
The syntax is "[[mung-trace-enable {ipc} {sched} {redir} {irq}]]". Label names
are mapped in exception.c:check_trace_control(), which should be kept up to
date with <ukernel/trace.h> as TRID_* symbols are added.

This replaces the old and bad mapdb_init() segment.