exception: fix KDB-entering int3
There's a special case for the test suite, where debug entry strings starting
with "mung " and ending with " do nothing" will simply return to userspace.
This exists so that testbench can invoke KDB without going into an interactive
mode; following testing against L4Ka::Pistachio (where such a feature doesn't
exist), that test should be skipped unless KIP identifies the kernel as mung.