exception: don't break userspace when warning about many faults
First, move the entire clause under DEBUG_ME_HARDER. Second, make it break at
1000 reps instead of 10. Third, don't halt the faulting thread.

The problem was that it's perfectly normal for some programs to e.g. use a
single page as a VM bounce buffer, causing repeated faulting on the same
address without indicating an actual problem. Unfortunately, code that was
supposed to halt a runaway situation would then also stop entirely valid
stuff. With this, it no longer does.