exception: report x86 #MF to userspace
The receiving exception handler may point the faulting thread (using
ExchangeRegisters) to a code fragment that captures the FPU status word and
acts accordingly, later popping an exception that lets the handler cause its
return to the x87 instruction that originally faulted.