exception: do lazy fill of page tables under catch_pf()
If the lazy fill succeeds, the handler returns to the faulting instruction. A
re-fault will cause the same fill to fail, triggering longjmp(). The repair
path hasn't been tested at all, but since space_prefill_upper() is known to
always return false on the second go, it's fair to assume that this isn't
outright broken.

The immediate upshot is that copy_intraspace_stritem() no longer needs to
repair pagefaults, so no more calls to mapdb_probe(), space_put_page(), or
(perhaps most importantly) tail recursion.