exception: fix reporting of kernel #PF
It no longer attempts to dereference a possibly-NULL `current'. Since that
case only happens from within the kernel, and in-kernel cases are the catch_pf
mechanism and kernel #PF errors, an assertion will fix the rest.